// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import path from 'node:path'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  migrate: {
    adapter: async () => {
      const { PrismaLibSQL } = await import('@prisma/adapter-libsql')
      const { createClient } = await import('@libsql/client')
      const client = createClient({
        url: `file:${path.join(process.cwd(), 'prisma', 'dev.db')}`,
      })
      return new PrismaLibSQL(client)
    },
  },
})